module Restaurants
  # PUBLIC api: a curated seed list of Austin restaurants plus an idempotent
  # seeding entrypoint the host (or a sibling) can call. Admins add more through
  # the in-app admin area; this just guarantees a non-empty starting set.
  module Catalog
    module_function

    SEED = [
      { name: "Franklin Barbecue", cuisine: "Barbecue", area: "East Austin" },
      { name: "Uchi", cuisine: "Sushi", area: "South Lamar" },
      { name: "Uchiko", cuisine: "Sushi", area: "Rosedale" },
      { name: "La Barbecue", cuisine: "Barbecue", area: "East Austin" },
      { name: "Veracruz All Natural", cuisine: "Tacos", area: "East Austin" },
      { name: "Suerte", cuisine: "Mexican", area: "East Austin" },
      { name: "Matt's El Rancho", cuisine: "Tex-Mex", area: "South Lamar" },
      { name: "Torchy's Tacos", cuisine: "Tacos", area: "South Congress" },
      { name: "Home Slice Pizza", cuisine: "Pizza", area: "South Congress" },
      { name: "Via 313", cuisine: "Pizza", area: "East Austin" },
      { name: "Salt & Time", cuisine: "Steakhouse", area: "East Austin" },
      { name: "Odd Duck", cuisine: "New American", area: "South Lamar" },
      { name: "Barley Swine", cuisine: "New American", area: "North Burnet" },
      { name: "Loro", cuisine: "Asian Barbecue", area: "South Lamar" },
      { name: "Ramen Tatsu-ya", cuisine: "Ramen", area: "South Lamar" },
      { name: "Kemuri Tatsu-ya", cuisine: "Izakaya", area: "East Austin" },
      { name: "Launderette", cuisine: "New American", area: "East Austin" },
      { name: "Jeffrey's", cuisine: "Fine Dining", area: "Clarksville" },
      { name: "Emmer & Rye", cuisine: "New American", area: "Rainey Street" },
      { name: "Joann's Fine Foods", cuisine: "Diner", area: "South Congress" },
      { name: "Hopdoddy Burger Bar", cuisine: "Burgers", area: "South Congress" },
      { name: "P. Terry's", cuisine: "Burgers", area: "Barton Springs" },
      { name: "Juan in a Million", cuisine: "Tex-Mex", area: "East Austin" },
      { name: "Curra's Grill", cuisine: "Mexican", area: "Travis Heights" },
      { name: "El Naranjo", cuisine: "Mexican", area: "Rainey Street" },
      { name: "Cooper's Old Time Pit Bar-B-Que", cuisine: "Barbecue", area: "Downtown" },
      { name: "Terry Black's Barbecue", cuisine: "Barbecue", area: "Barton Springs" },
      { name: "Micklethwait Craft Meats", cuisine: "Barbecue", area: "East Austin" },
      { name: "Lin Asian Bar", cuisine: "Dumplings", area: "Clarksville" },
      { name: "Sichuan River", cuisine: "Sichuan", area: "North Austin" },
      { name: "Aviary Wine & Kitchen", cuisine: "Wine Bar", area: "South Lamar" },
      { name: "Olamaie", cuisine: "Southern", area: "Downtown" },
      { name: "Comedor", cuisine: "Mexican", area: "Downtown" },
      { name: "Dai Due", cuisine: "Farm-to-Table", area: "East Austin" },
      { name: "Birdie's", cuisine: "New American", area: "East Austin" },
      { name: "Nixta Taqueria", cuisine: "Tacos", area: "East Austin" },
      { name: "Cuantos Tacos", cuisine: "Tacos", area: "East Austin" },
      { name: "Sam's Bar-B-Que", cuisine: "Barbecue", area: "East Austin" },
      { name: "Fonda San Miguel", cuisine: "Mexican", area: "North Loop" },
      { name: "Clark's Oyster Bar", cuisine: "Seafood", area: "Clarksville" },
      { name: "Contigo", cuisine: "New American", area: "Mueller" },
      { name: "Justine's Brasserie", cuisine: "French", area: "East Austin" },
      { name: "Rye", cuisine: "New American", area: "East Austin" },
      { name: "Otoko", cuisine: "Sushi", area: "South Congress" },
      { name: "Kome Sushi Kitchen", cuisine: "Japanese", area: "North Loop" },
      { name: "Wu Chow", cuisine: "Chinese", area: "Downtown" },
      { name: "Din Ho Chinese BBQ", cuisine: "Chinese", area: "North Austin" },
      { name: "Old Thousand", cuisine: "Sichuan", area: "East Austin" },
      { name: "The Peached Tortilla", cuisine: "Asian Fusion", area: "South Lamar" },
      { name: "Gourdough's Big. Fat. Donuts.", cuisine: "Donuts", area: "South Austin" },
      { name: "Guero's Taco Bar", cuisine: "Tex-Mex", area: "South Congress" },
      { name: "El Alma Cafe & Cantina", cuisine: "Mexican", area: "South Congress" },
      { name: "Cisco's Restaurant", cuisine: "Tex-Mex", area: "East Austin" },
      { name: "Tamale House East", cuisine: "Tex-Mex", area: "East Austin" },
      { name: "Rosita's Al Pastor", cuisine: "Tacos", area: "East Austin" },
      { name: "Valentina's Tex Mex BBQ", cuisine: "Barbecue", area: "South Austin" },
      { name: "Interstellar BBQ", cuisine: "Barbecue", area: "East Austin" },
      { name: "LeRoy and Lewis Barbecue", cuisine: "Barbecue", area: "South Austin" },
      { name: "Stiles Switch BBQ", cuisine: "Barbecue", area: "North Austin" },
      { name: "Rudy's Country Store and Bar-B-Q", cuisine: "Barbecue", area: "North Austin" },
      { name: "The Salt Lick", cuisine: "Barbecue", area: "Driftwood" },
      { name: "County Line", cuisine: "Barbecue", area: "Bee Cave Road" },
      { name: "Iron Works Barbecue", cuisine: "Barbecue", area: "Downtown" },
      { name: "Distant Relatives BBQ", cuisine: "Barbecue", area: "East Austin" },
      { name: "Pieous", cuisine: "Wood-Fired Pizza", area: "Cedar Park" },
      { name: "Bufalina", cuisine: "Pizza", area: "East Austin" },
      { name: "Little Deli & Pizzeria", cuisine: "Pizza", area: "Clarksville" },
      { name: "East Side Pies", cuisine: "Pizza", area: "East Austin" },
      { name: "Southside Flying Pizza", cuisine: "Pizza", area: "Zilker" },
      { name: "Pinthouse Pizza", cuisine: "Pizza & Beer", area: "North Austin" },
      { name: "Patrizi's", cuisine: "Italian", area: "South Austin" },
      { name: "L'Oca d'Oro", cuisine: "Italian", area: "East Austin" },
      { name: "Red Ash", cuisine: "Italian", area: "Domain" },
      { name: "Andiamo Ristorante", cuisine: "Italian", area: "North Austin" },
      { name: "Vespaio", cuisine: "Italian", area: "South Congress" },
      { name: "Enoteca Vespaio", cuisine: "Italian", area: "South Congress" },
      { name: "Il Brutto", cuisine: "Italian", area: "East Austin" },
      { name: "Second Bar + Kitchen", cuisine: "New American", area: "Downtown" },
      { name: "Michi Ramen", cuisine: "Ramen", area: "South Lamar" },
      { name: "Daruma Ramen", cuisine: "Ramen", area: "North Austin" },
      { name: "Kirin Court", cuisine: "Chinese", area: "North Austin" },
      { name: "Titaya's Thai Cuisine", cuisine: "Thai", area: "North Austin" },
      { name: "Thai Fresh", cuisine: "Thai", area: "Bouldin Creek" },
      { name: "Sway", cuisine: "Thai", area: "Downtown" },
      { name: "Swadee Thai", cuisine: "Thai", area: "South Austin" },
      { name: "Perla's Seafood and Oyster Bar", cuisine: "Seafood", area: "South Congress" },
      { name: "Quality Seafood Market", cuisine: "Seafood", area: "Hyde Park" },
      { name: "Cherry Creek Catfish", cuisine: "Seafood", area: "South Austin" },
      { name: "Moonshine Patio Bar & Grill", cuisine: "Southern", area: "Downtown" },
      { name: "Hillside Farmacy", cuisine: "New American", area: "East Austin" },
      { name: "June's All Day", cuisine: "Wine Bar", area: "South Congress" },
      { name: "Elizabeth Street Cafe", cuisine: "Vietnamese-French", area: "Bouldin Creek" },
      { name: "Nasha's Ethiopian Kitchen", cuisine: "Ethiopian", area: "East Austin" },
      { name: "Kerbey Lane Cafe", cuisine: "Diner", area: "Central Austin" },
      { name: "Magnolia Cafe", cuisine: "Diner", area: "South Congress" },
      { name: "Shady Grove", cuisine: "American", area: "Barton Springs" },
      { name: "Threadgill's", cuisine: "Southern", area: "North Loop" },
      { name: "Dirty Martin's Place", cuisine: "Burgers", area: "West Campus" },
      { name: "Casino El Camino", cuisine: "Burgers", area: "Downtown" },
      { name: "Top Notch Hamburgers", cuisine: "Burgers", area: "South Austin" },
      { name: "Bartlett's", cuisine: "American", area: "Central Austin" },
      { name: "Fixe", cuisine: "Southern", area: "Downtown" },
      { name: "Eberly", cuisine: "New American", area: "South Austin" },
      { name: "Foreign & Domestic", cuisine: "New American", area: "North Loop" },
      { name: "Chuy's", cuisine: "Tex-Mex", area: "Barton Springs" },
      { name: "Trudy's Texas Star", cuisine: "Tex-Mex", area: "North Austin" },
      { name: "Maudie's Tex-Mex", cuisine: "Tex-Mex", area: "South Lamar" },
      { name: "Manuel's", cuisine: "Tex-Mex", area: "Downtown" },
      { name: "Habanero Mexican Cafe", cuisine: "Mexican", area: "South Austin" }
    ].freeze

    def seed!
      SEED.each do |attrs|
        Restaurants::Restaurant.find_or_create_by!(name: attrs[:name]) do |r|
          r.cuisine = attrs[:cuisine]
          r.area = attrs[:area]
        end
      end
    end
  end
end
